-- GENERATED by capnut_migration.staging — do not edit by hand.
-- Regenerate with:  capnut-migrate schema --write
--
-- One generic landing table, one typed view per dataset. Source identifiers are
-- preserved verbatim in source_id and are the primary key alongside the
-- snapshot label, so re-running an extraction into the same snapshot updates
-- rows instead of duplicating them.

CREATE SCHEMA IF NOT EXISTS stg;

CREATE TABLE IF NOT EXISTS stg.snapshot (
    label           text PRIMARY KEY,
    source_system   text        NOT NULL,
    source_adapter  text        NOT NULL,
    cutover_date    date        NOT NULL,
    as_of           date        NOT NULL,
    info            jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stg.record (
    snapshot        text        NOT NULL REFERENCES stg.snapshot(label) ON DELETE CASCADE,
    dataset         text        NOT NULL,
    source_system   text        NOT NULL,
    source_id       text        NOT NULL,
    payload         jsonb       NOT NULL,
    extracted_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (snapshot, dataset, source_id)
);

CREATE INDEX IF NOT EXISTS record_dataset_idx ON stg.record (snapshot, dataset);

CREATE TABLE IF NOT EXISTS stg.extract_log (
    snapshot        text        NOT NULL,
    dataset         text        NOT NULL,
    row_count       bigint      NOT NULL,
    digest          text        NOT NULL,
    started_at      timestamptz NOT NULL,
    finished_at     timestamptz NOT NULL,
    PRIMARY KEY (snapshot, dataset, finished_at)
);

-- Chart of accounts
CREATE OR REPLACE VIEW stg.accounts AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'code')::text AS code,
    (payload ->> 'name')::text AS name,
    (payload ->> 'account_type')::text AS account_type,
    (payload ->> 'reconcile')::boolean AS reconcile,
    (payload ->> 'deprecated')::boolean AS deprecated,
    (payload ->> 'currency')::text AS currency
FROM stg.record
WHERE dataset = 'accounts';

-- Journals
CREATE OR REPLACE VIEW stg.journals AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'code')::text AS code,
    (payload ->> 'name')::text AS name,
    (payload ->> 'journal_type')::text AS journal_type,
    (payload ->> 'currency')::text AS currency
FROM stg.record
WHERE dataset = 'journals';

-- Taxes
CREATE OR REPLACE VIEW stg.taxes AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'name')::text AS name,
    (payload ->> 'amount')::numeric(18,2) AS amount,
    (payload ->> 'amount_type')::numeric(18,2) AS amount_type,
    (payload ->> 'type_tax_use')::text AS type_tax_use,
    (payload ->> 'active')::boolean AS active
FROM stg.record
WHERE dataset = 'taxes';

-- Customers and vendors
CREATE OR REPLACE VIEW stg.parties AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'ref')::text AS ref,
    (payload ->> 'name')::text AS name,
    (payload ->> 'is_company')::boolean AS is_company,
    (payload ->> 'parent_id')::bigint AS parent_id,
    (payload ->> 'customer_rank')::integer AS customer_rank,
    (payload ->> 'supplier_rank')::integer AS supplier_rank,
    (payload ->> 'vat')::text AS vat,
    (payload ->> 'email')::text AS email,
    (payload ->> 'phone')::text AS phone,
    (payload ->> 'street')::text AS street,
    (payload ->> 'street2')::text AS street2,
    (payload ->> 'city')::text AS city,
    (payload ->> 'state_code')::text AS state_code,
    (payload ->> 'zip')::text AS zip,
    (payload ->> 'country_code')::text AS country_code,
    (payload ->> 'active')::boolean AS active
FROM stg.record
WHERE dataset = 'parties';

-- Products (variants)
CREATE OR REPLACE VIEW stg.products AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'template_id')::bigint AS template_id,
    (payload ->> 'default_code')::text AS default_code,
    (payload ->> 'barcode')::text AS barcode,
    (payload ->> 'name')::text AS name,
    (payload ->> 'product_type')::text AS product_type,
    (payload ->> 'uom')::text AS uom,
    (payload ->> 'list_price')::numeric(18,6) AS list_price,
    (payload ->> 'standard_price')::numeric(18,6) AS standard_price,
    (payload ->> 'categ_name')::text AS categ_name,
    (payload ->> 'active')::boolean AS active
FROM stg.record
WHERE dataset = 'products';

-- Posted GL lines up to the as-of date
CREATE OR REPLACE VIEW stg.gl_lines AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'move_id')::bigint AS move_id,
    (payload ->> 'move_name')::text AS move_name,
    (payload ->> 'date')::date AS date,
    (payload ->> 'journal_code')::text AS journal_code,
    (payload ->> 'account_code')::text AS account_code,
    (payload ->> 'account_id')::bigint AS account_id,
    (payload ->> 'partner_id')::bigint AS partner_id,
    (payload ->> 'debit')::numeric(18,2) AS debit,
    (payload ->> 'credit')::numeric(18,2) AS credit,
    (payload ->> 'balance')::numeric(18,2) AS balance,
    (payload ->> 'currency')::text AS currency,
    (payload ->> 'amount_currency')::numeric(18,2) AS amount_currency,
    (payload ->> 'label')::text AS label
FROM stg.record
WHERE dataset = 'gl_lines';

-- Open customer invoices and credit notes
CREATE OR REPLACE VIEW stg.ar_open AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'number')::text AS number,
    (payload ->> 'move_type')::text AS move_type,
    (payload ->> 'partner_id')::bigint AS partner_id,
    (payload ->> 'partner_ref')::text AS partner_ref,
    (payload ->> 'date')::date AS date,
    (payload ->> 'due_date')::date AS due_date,
    (payload ->> 'currency')::text AS currency,
    (payload ->> 'amount_total')::numeric(18,2) AS amount_total,
    (payload ->> 'amount_residual')::numeric(18,2) AS amount_residual,
    (payload ->> 'account_code')::text AS account_code,
    (payload ->> 'state')::text AS state
FROM stg.record
WHERE dataset = 'ar_open';

-- Open vendor bills and refunds
CREATE OR REPLACE VIEW stg.ap_open AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'number')::text AS number,
    (payload ->> 'move_type')::text AS move_type,
    (payload ->> 'partner_id')::bigint AS partner_id,
    (payload ->> 'partner_ref')::text AS partner_ref,
    (payload ->> 'date')::date AS date,
    (payload ->> 'due_date')::date AS due_date,
    (payload ->> 'currency')::text AS currency,
    (payload ->> 'amount_total')::numeric(18,2) AS amount_total,
    (payload ->> 'amount_residual')::numeric(18,2) AS amount_residual,
    (payload ->> 'account_code')::text AS account_code,
    (payload ->> 'state')::text AS state
FROM stg.record
WHERE dataset = 'ap_open';

-- Approved purchase orders not fully received/billed
CREATE OR REPLACE VIEW stg.open_pos AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'name')::text AS name,
    (payload ->> 'partner_id')::bigint AS partner_id,
    (payload ->> 'date_order')::date AS date_order,
    (payload ->> 'state')::text AS state,
    (payload ->> 'currency')::text AS currency,
    (payload ->> 'amount_untaxed')::numeric(18,2) AS amount_untaxed,
    (payload ->> 'amount_total')::numeric(18,2) AS amount_total
FROM stg.record
WHERE dataset = 'open_pos';

-- Lines of the approved open POs
CREATE OR REPLACE VIEW stg.open_po_lines AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'order_id')::bigint AS order_id,
    (payload ->> 'order_name')::text AS order_name,
    (payload ->> 'product_id')::bigint AS product_id,
    (payload ->> 'product_code')::text AS product_code,
    (payload ->> 'description')::text AS description,
    (payload ->> 'qty_ordered')::numeric(18,6) AS qty_ordered,
    (payload ->> 'qty_received')::numeric(18,6) AS qty_received,
    (payload ->> 'qty_invoiced')::numeric(18,6) AS qty_invoiced,
    (payload ->> 'qty_open')::numeric(18,6) AS qty_open,
    (payload ->> 'price_unit')::numeric(18,6) AS price_unit,
    (payload ->> 'line_total')::numeric(18,2) AS line_total,
    (payload ->> 'uom')::text AS uom,
    (payload ->> 'date_planned')::date AS date_planned
FROM stg.record
WHERE dataset = 'open_po_lines';

-- On-hand quantity and value by product and location
CREATE OR REPLACE VIEW stg.inventory AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'product_id')::bigint AS product_id,
    (payload ->> 'product_code')::text AS product_code,
    (payload ->> 'location_id')::bigint AS location_id,
    (payload ->> 'location_name')::text AS location_name,
    (payload ->> 'internal')::boolean AS internal,
    (payload ->> 'quantity')::numeric(18,6) AS quantity,
    (payload ->> 'unit_cost')::numeric(18,6) AS unit_cost,
    (payload ->> 'value')::numeric(18,2) AS value
FROM stg.record
WHERE dataset = 'inventory';

-- Sales orders (history and reference)
CREATE OR REPLACE VIEW stg.sales_orders AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'name')::text AS name,
    (payload ->> 'partner_id')::bigint AS partner_id,
    (payload ->> 'date_order')::date AS date_order,
    (payload ->> 'state')::text AS state,
    (payload ->> 'currency')::text AS currency,
    (payload ->> 'amount_untaxed')::numeric(18,2) AS amount_untaxed,
    (payload ->> 'amount_tax')::numeric(18,2) AS amount_tax,
    (payload ->> 'amount_total')::numeric(18,2) AS amount_total
FROM stg.record
WHERE dataset = 'sales_orders';

-- Customer and vendor payments
CREATE OR REPLACE VIEW stg.payments AS
SELECT
    snapshot,
    source_system,
    (payload ->> 'source_id')::bigint AS source_id,
    (payload ->> 'name')::text AS name,
    (payload ->> 'payment_type')::text AS payment_type,
    (payload ->> 'partner_id')::bigint AS partner_id,
    (payload ->> 'date')::date AS date,
    (payload ->> 'currency')::text AS currency,
    (payload ->> 'amount')::numeric(18,2) AS amount,
    (payload ->> 'journal_code')::text AS journal_code,
    (payload ->> 'state')::text AS state
FROM stg.record
WHERE dataset = 'payments';
