"""Staging schema.

Extraction writes JSONL to disk first — that artifact is the snapshot, it needs
no database, and it can be diffed between rehearsals. ``stage`` then loads those
files into PostgreSQL so an accountant can query the source with SQL.

The physical model is one generic table plus one typed view per dataset. The
views are generated from the dataset catalogue, so a new dataset cannot drift
out of sync with its staging table.

Column types are assigned by naming convention (documented in TYPE_RULES). Keep
column names boring and the types come out right.
"""

from __future__ import annotations

from .sources.base import DATASETS, Dataset

SCHEMA = "stg"

# (matcher, sql type). First match wins; order matters.
TYPE_RULES: tuple[tuple[str, str], ...] = (
    ("source_id", "bigint"),
    ("*_id", "bigint"),
    ("date*", "date"),
    ("*_date", "date"),
    ("debit", "numeric(18,2)"),
    ("credit", "numeric(18,2)"),
    ("balance", "numeric(18,2)"),
    ("amount*", "numeric(18,2)"),
    ("*_total", "numeric(18,2)"),
    ("value", "numeric(18,2)"),
    ("price*", "numeric(18,6)"),
    ("*_price", "numeric(18,6)"),
    ("*_cost", "numeric(18,6)"),
    ("qty*", "numeric(18,6)"),
    ("quantity", "numeric(18,6)"),
    ("amount", "numeric(18,2)"),
    ("active", "boolean"),
    ("internal", "boolean"),
    ("reconcile", "boolean"),
    ("deprecated", "boolean"),
    ("is_*", "boolean"),
    ("*_rank", "integer"),
)


def _matches(pattern: str, name: str) -> bool:
    if pattern.startswith("*") and pattern.endswith("*"):
        return pattern.strip("*") in name
    if pattern.startswith("*"):
        return name.endswith(pattern[1:])
    if pattern.endswith("*"):
        return name.startswith(pattern[:-1])
    return name == pattern


def sql_type(column: str) -> str:
    for pattern, sqltype in TYPE_RULES:
        if _matches(pattern, column):
            return sqltype
    return "text"


def view_ddl(ds: Dataset) -> str:
    cols = ",\n".join(
        f"    (payload ->> '{c}')::{sql_type(c)} AS {c}" for c in ds.columns
    )
    return (
        f"-- {ds.description}\n"
        f"CREATE OR REPLACE VIEW {SCHEMA}.{ds.name} AS\nSELECT\n"
        f"    snapshot,\n    source_system,\n{cols}\n"
        f"FROM {SCHEMA}.record\nWHERE dataset = '{ds.name}';\n"
    )


def generate_ddl(datasets: tuple[Dataset, ...] = DATASETS) -> str:
    header = f"""-- GENERATED by capnut_migration.staging — do not edit by hand.
-- Regenerate with:  capnut-migrate schema --write
--
-- One generic landing table, one typed view per dataset. Source identifiers are
-- preserved verbatim in source_id and are the primary key alongside the
-- snapshot label, so re-running an extraction into the same snapshot updates
-- rows instead of duplicating them.

CREATE SCHEMA IF NOT EXISTS {SCHEMA};

CREATE TABLE IF NOT EXISTS {SCHEMA}.snapshot (
    label           text PRIMARY KEY,
    source_system   text        NOT NULL,
    source_adapter  text        NOT NULL,
    cutover_date    date        NOT NULL,
    as_of           date        NOT NULL,
    info            jsonb       NOT NULL DEFAULT '{{}}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS {SCHEMA}.record (
    snapshot        text        NOT NULL REFERENCES {SCHEMA}.snapshot(label) ON DELETE CASCADE,
    dataset         text        NOT NULL,
    source_system   text        NOT NULL,
    source_id       text        NOT NULL,
    payload         jsonb       NOT NULL,
    extracted_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (snapshot, dataset, source_id)
);

CREATE INDEX IF NOT EXISTS record_dataset_idx ON {SCHEMA}.record (snapshot, dataset);

CREATE TABLE IF NOT EXISTS {SCHEMA}.extract_log (
    snapshot        text        NOT NULL,
    dataset         text        NOT NULL,
    row_count       bigint      NOT NULL,
    digest          text        NOT NULL,
    started_at      timestamptz NOT NULL,
    finished_at     timestamptz NOT NULL,
    PRIMARY KEY (snapshot, dataset, finished_at)
);

"""
    return header + "\n".join(view_ddl(ds) for ds in datasets)
